import { DELIVERY_ZIPS } from "@/content/zips";
import {
  ZONE_POLYGONS,
  ZONE_VIEWBOX,
  BASEMAP,
} from "@/content/delivery-zone";

/**
 * Delivery zone drawn from real US Census ZIP boundaries, over a baked
 * OpenStreetMap road basemap. Both are generated by
 * scripts/build-delivery-zone.mjs — read that before changing anything here.
 */
export function DeliveryAreaMap() {
  const { width, height } = ZONE_VIEWBOX;

  // No caption inside this card — whatever section embeds it already names the
  // zone, and two headings stacked on one map read as a mistake.
  return (
    <figure className="bg-(--bg-card) border border-(--color-line) rounded-2xl p-4 sm:p-6">
      <div className="relative w-full max-w-md mx-auto">
        <svg
          viewBox={`0 0 ${width} ${height}`}
          role="img"
          aria-label={`Map of the Iron Oaks delivery zone: ZIP codes ${[...DELIVERY_ZIPS]
            .sort()
            .join(", ")} across north Austin, Round Rock, and Pflugerville.`}
          className="w-full h-auto"
        >
          <defs>
            <linearGradient id="zone-fill" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#D89A3A" stopOpacity="0.30" />
              <stop offset="100%" stopColor="#D89A3A" stopOpacity="0.14" />
            </linearGradient>
          </defs>

          <clipPath id="map-round">
            <rect x="0" y="0" width={width} height={height} rx="10" />
          </clipPath>

          {/* Everything outside the delivery zone, for dimming it back. */}
          <mask id="outside-zone">
            <rect x="0" y="0" width={width} height={height} fill="white" />
            <g fill="black">
              {ZONE_POLYGONS.map((p) => (
                <path key={p.zip} d={p.d} />
              ))}
            </g>
          </mask>

          <g clipPath="url(#map-round)">
            <rect x="0" y="0" width={width} height={height} fill="#1C1A17" />
            {/* Road basemap, generated to match this viewBox exactly. */}
            <image
              href={BASEMAP.src}
              x="0"
              y="0"
              width={width}
              height={height}
              preserveAspectRatio="none"
            />
            {/* Spotlight: the area we don't deliver to drops back hard, so the
                zone reads at a glance instead of competing with the roads. */}
            <g mask="url(#outside-zone)">
              <rect
                x="0"
                y="0"
                width={width}
                height={height}
                fill="#0B0A09"
                opacity="0.48"
              />
            </g>

            {/* Zone: fills first, then one pass of borders so shared edges
                between neighbouring ZIPs don't double up. */}
            <g>
              {ZONE_POLYGONS.map((p) => (
                <path key={p.zip} d={p.d} fill="url(#zone-fill)" />
              ))}
            </g>
            <g fill="none" stroke="#E0A544" strokeOpacity="0.9" strokeWidth="1.6">
              {ZONE_POLYGONS.map((p) => (
                <path key={p.zip} d={p.d} />
              ))}
            </g>
          </g>

          {/* No truck pin — Edward is delivery-only for now, so the map shows
              who gets delivered to, not where the truck parks. TRUCK_POINT is
              still generated and still frames the view; restore the pin here
              alongside pickup. */}

          {/* Labels sit on top of printed road names, so every one gets a dark
              halo via paint-order: stroke. Without it they're unreadable. */}
          <g
            fontFamily="ui-sans-serif, system-ui, sans-serif"
            paintOrder="stroke"
            stroke="#0B0A09"
            strokeOpacity="0.85"
            strokeLinejoin="round"
            pointerEvents="none"
          >
            <g textAnchor="middle">
              {ZONE_POLYGONS.map((p) => (
                <g key={p.zip}>
                  <text
                    x={p.cx}
                    y={p.cy}
                    fontSize="18"
                    fontWeight="700"
                    fill="#F5EFE5"
                    letterSpacing="0.5"
                    strokeWidth="4"
                  >
                    {p.zip}
                  </text>
                  <text
                    x={p.cx}
                    y={p.cy + 15}
                    fontSize="11"
                    fill="#D7CEC0"
                    letterSpacing="0.4"
                    strokeWidth="3"
                  >
                    {p.city}
                  </text>
                </g>
              ))}
            </g>
          </g>
        </svg>

      </div>

      <p className="mt-5 text-xs text-(--text-muted) text-center">
        Boundaries: US Census ZIP Code Tabulation Areas. Map data{" "}
        {BASEMAP.attribution}. Confirm your address at checkout.
      </p>
    </figure>
  );
}
